/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2016-02-05 11:30:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en-US\">\n");
      out.write("   \t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"></meta>\n");
      out.write("\t<script src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("/*CSS for input textbox and password*/\n");
      out.write("\n");
      out.write("\n");
      out.write("input[type='text']\n");
      out.write("{\n");
      out.write("width: 200px;\n");
      out.write("height: 35px;\n");
      out.write("border-radius: 3px;\n");
      out.write("border: 1px solid #CCC;\n");
      out.write("padding: 8px;\n");
      out.write("font-weight: 200;\n");
      out.write("font-size: 15px;\n");
      out.write("font-family: Verdana;\n");
      out.write("box-shadow: 1px 1px 5px #CCC;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type='text']:hover\n");
      out.write("{\n");
      out.write("width: 200px;\n");
      out.write("height: 35px;\n");
      out.write("border-radius: 3px;\n");
      out.write("border: 1px solid #aaa;\n");
      out.write("padding: 8px;\n");
      out.write("font-weight: 200;\n");
      out.write("font-size: 15px;\n");
      out.write("font-family: Verdana;\n");
      out.write("box-shadow: 1px 1px 5px #CCC;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("input[type='password']\n");
      out.write("{\n");
      out.write("width: 200px;\n");
      out.write("height: 35px;\n");
      out.write("border-radius: 3px;\n");
      out.write("border: 1px solid #CCC;\n");
      out.write("padding: 8px;\n");
      out.write("font-weight: 200;\n");
      out.write("font-size: 15px;\n");
      out.write("font-family: Verdana;\n");
      out.write("box-shadow: 1px 1px 5px #CCC;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("input[type='password']:hover\n");
      out.write("{\n");
      out.write("width: 200px;\n");
      out.write("height: 35px;\n");
      out.write("border-radius: 3px;\n");
      out.write("border: 1px solid #aaa;\n");
      out.write("padding: 8px;\n");
      out.write("font-weight: 200;\n");
      out.write("font-size: 15px;\n");
      out.write("font-family: Verdana;\n");
      out.write("box-shadow: 1px 1px 5px #CCC;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("/*input type for submit button*/\n");
      out.write("\n");
      out.write("input[type='button']\n");
      out.write("{\n");
      out.write("width: 150px;\n");
      out.write("height: 40px;\n");
      out.write("border: 2px solid white;\n");
      out.write("font-weight: 200;\n");
      out.write("font-size: 15px;\n");
      out.write("font-family: Verdana;\n");
      out.write("background-color:#CCC;\n");
      out.write("}\n");
      out.write("input[type='button']:hover\n");
      out.write("{\n");
      out.write("width: 150px;\n");
      out.write("height: 40px;\n");
      out.write("border: 2px solid #aaa;\n");
      out.write("font-weight: 200;\n");
      out.write("font-size: 15px;\n");
      out.write("font-family: Verdana;\n");
      out.write("background-color:#000000;\n");
      out.write("color:#fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*Table*/\n");
      out.write(".outer {\n");
      out.write("    width: 960px;\n");
      out.write("    color: navy;\n");
      out.write("    background-color: #CCC;\n");
      out.write("    border: 2px solid #aaa;\n");
      out.write("    padding: 5px;\n");
      out.write(" }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("<div ng-app=\"LoginApp\" ng-controller=\"login\"> \n");
      out.write("<h1>\n");
      out.write("\t\tLogin Application\n");
      out.write("</h1>\n");
      out.write("\n");
      out.write("\n");
      out.write("<table >\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t<h2>\n");
      out.write("\t\tUserName :\n");
      out.write("\t</h2>\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t<input type=\"text\" ng-model=\"id\" >  \n");
      out.write("\t\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write("\t<td>\n");
      out.write("\t<h2>\n");
      out.write("\t\tPassword :\n");
      out.write("\t</h2>\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t\t<input type=\"password\" ng-model=\"pass\" > \n");
      out.write("\t\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<input type =\"button\" ng-click=\"login()\" value=\"Login\"><br>\n");
      out.write("<P>\n");
      out.write("<h1>\n");
      out.write("<a ng-href=\"register.jsp\">Register New User..</a>\n");
      out.write("</h1>\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("  <p ng-show=\"flag1\">\n");
      out.write("\t\tLogin Successful...!\n");
      out.write("\t</p>\n");
      out.write("\t<p ng-show=\"flag2\">\n");
      out.write("\t\tUnsuccessful...!\n");
      out.write("\t</p>-->\n");
      out.write(" </div>   \n");
      out.write("\n");
      out.write("<script>\n");
      out.write("var app = angular.module('LoginApp', []);\n");
      out.write("app.controller('login', function($scope, $http) {\n");
      out.write("\t$scope.flag = false;\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t$scope.getuser = function() {\n");
      out.write("\t\t\n");
      out.write("\t    $http.get(\"http://localhost:8080/LoginApp/users\")\n");
      out.write("\t    .success(function(response) {$scope.employee=response;});\n");
      out.write("\t    $scope.users=null;\n");
      out.write("\t    $scope.flag = true;\n");
      out.write("\t \n");
      out.write("\t};\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t$scope.login = function() {\n");
      out.write("\t\t//alert(\"In display\");\n");
      out.write("\t    \n");
      out.write("\t\t$scope.flag1 = false;\n");
      out.write("\t\t$scope.flag2 = false;\n");
      out.write("\t\t\n");
      out.write("\t\t$http.get(\"http://localhost:8080/LoginApp/login/\"+ $scope.id + \"/\" + $scope.pass)\n");
      out.write("\t    .success(function(response) {$scope.msg=response;\n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t    if($scope.msg==1)\n");
      out.write("\t\t\t{\n");
      out.write("\t    \t$scope.flag1 = true;\n");
      out.write("\t\t\talert(\"Login Succesful..!!\");\n");
      out.write("\t\t\t}\n");
      out.write("\t    else\n");
      out.write("\t    \t{\n");
      out.write("\t\t\t$scope.flag2 = true;\n");
      out.write("\t\t\talert(\"Login unsuceesful..!!\");\n");
      out.write("\t    \t}\n");
      out.write("\t    \n");
      out.write("\t    });\n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t   \n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("/*\n");
      out.write("\t$scope.all = function() {\n");
      out.write("\t\talert(\"login...\");\t\t\n");
      out.write("\t\t$scope.employee=null;\n");
      out.write("\t    $http.get(\"http://localhost:8080/LoginApp/login/\" + $scope.id + \"/\" + $scope.pass)\n");
      out.write("\t    .success(function(response) {$scope.status=response;});\n");
      out.write("\t    alert($scope.status);\t \n");
      out.write("\t    $scope.flag = true;\n");
      out.write("\t \n");
      out.write("\t}; */\n");
      out.write("\t/*\n");
      out.write("\t$scope.login = function() {\n");
      out.write("\t\talert(\"In login...before .get\");\n");
      out.write("\t    $http.get(\"http://localhost:8080/LoginApp/login/\" + $scope.id + \"/\" + $scope.pass)\n");
      out.write("\t    .success(function(response) {$scope.msg=response;});    \t    \n");
      out.write("\t  */\n");
      out.write("\t    /*\n");
      out.write("\t    if($scope.msg == false)\n");
      out.write("\t\t{\n");
      out.write("\t\t\talert(\"Trade is Successful..!\");\n");
      out.write("\t\t}\n");
      out.write("\telse\n");
      out.write("\t\t{\n");
      out.write("\t\t\n");
      out.write("\t\t\talert(\"Trade is unsuccessful..!\");\n");
      out.write("\t\t}\n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t    */\n");
      out.write("\t    \n");
      out.write("\t    //alert(\"Message is \"+$scope.msg);\n");
      out.write("\t    //$scope.users=null;\n");
      out.write("\t    //$scope.flag = true;\t \n");
      out.write("\t\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body></html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
